# 2021.3.8 Numpy的矩阵计算和统计分析功能

## 1. Numpy的矩阵计算

In [1]:
import numpy as np

### 1.1Numpy的matrix类

numpy中有一种numpy.matrix类，专门用来表示矩阵，但是已经不推荐使用了，https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [2]:
x = np.array([[1, 2], [3, 4]])
print(type(x))
print(x)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


class numpy.matrix(data, dtype=None, copy=True)

In [3]:
#ndarray可以转换为matrix
m=np.matrix(x)
print(type(m))
print(m)

<class 'numpy.matrix'>
[[1 2]
 [3 4]]


In [4]:
m_matrix=np.matrix(x)
m_mat = np.mat(x)  #等效于asmatrix，作为一个矩阵
m_asmatrix=np.asmatrix(x)
print('\n',m_matrix,'\n',type(m_matrix),'\n\n',m_mat,'\n',type(m_mat),'\n\n',m_asmatrix,'\n',type(m_asmatrix))


 [[1 2]
 [3 4]] 
 <class 'numpy.matrix'> 

 [[1 2]
 [3 4]] 
 <class 'numpy.matrix'> 

 [[1 2]
 [3 4]] 
 <class 'numpy.matrix'>


In [5]:
m_matrix[0,0]=10
print(x,'\n\n',m_matrix)

[[1 2]
 [3 4]] 

 [[10  2]
 [ 3  4]]


In [6]:
m_mat[0,1]=20
print(x,'\n\n',m_mat)

[[ 1 20]
 [ 3  4]] 

 [[ 1 20]
 [ 3  4]]


In [7]:
type(x)

numpy.ndarray

In [8]:
m_asmatrix[1,0]=30
print(x,'\n\n',m_asmatrix)

[[ 1 20]
 [30  4]] 

 [[ 1 20]
 [30  4]]


In [9]:
type(x)

numpy.ndarray

**numpy.asmatrix(data, dtype=None)和 matrix(data, copy=False)等效**

In [10]:
#构建矩阵
matr1 = np.matrix("1 2 3;4 5 6;7 8 9")
matr2 = np.matrix('1,2,3;4,5,6;7,8,9') #用字符串构建矩阵，空格或逗号可以表示换列，分号表示换行
matr3 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(matr1,'\n\n',matr2,'\n\n',matr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
type(matr3)

numpy.matrix

In [14]:
matr4 = np.matrix("1 2 3;4 5 6;7 8") #在构建矩阵时，元素要整齐，整数行，整数列，不能缺项

ValueError: Rows not the same size.

In [16]:
matr5 = np.matrix("1 2 3;4 5 6;7 8 a") #矩阵的元素必须是同类型

ValueError: malformed node or string: <_ast.Name object at 0x000001F08284B988>

In [17]:
matr6 = np.matrix("a b c;d e f;g h i") #矩阵的元素必须是数字，比数组更为严格

ValueError: malformed node or string: <_ast.Name object at 0x000001F083860CC8>

In [18]:
matr6 = np.matrix("1.4 3.2 2.5;1.9 0.9 -2;-1.89 0.1 0.57")

In [19]:
print(matr6)

[[ 1.4   3.2   2.5 ]
 [ 1.9   0.9  -2.  ]
 [-1.89  0.1   0.57]]


In [20]:
#矩阵组合
#print(np.bmat('matr1,matr2'))
#print(np.bmat('matr1,matr2;matr2,matr3'))
print(np.bmat([[matr1,matr2],[matr2,matr3]]))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


### 1.2 numpy.mateix的矩阵运算

In [21]:
print(matr1,matr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
# 矩阵加减法
print(matr1+matr2)
print(matr1-matr2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
# 矩阵点乘
print(matr1*3)
a=5
print(a*matr2)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [26]:
# 矩阵叉乘
matr6=matr1*matr2
print(matr6)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [31]:
# 矩阵乘幂
matr1**4

matrix([[ 7560,  9288, 11016],
        [17118, 21033, 24948],
        [26676, 32778, 38880]])

In [32]:
# 矩阵对应位置相乘
np.multiply(matr1,matr2)

matrix([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [33]:
# 矩阵的转置
print(matr1.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
matr4=np.matrix('1,-3,0+1j;2,9,1-1j') #复数
# 共轭转置
print(matr4.H)

[[ 1.-0.j  2.-0.j]
 [-3.-0.j  9.-0.j]
 [ 0.-1.j  1.+1.j]]


In [37]:
matr5=np.matrix("1,0,0;0,2,0;0,0,1")
# 矩阵的逆
print(matr5,'\n\n',matr5.I)

[[1 0 0]
 [0 2 0]
 [0 0 1]] 

 [[1.  0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  1. ]]


In [38]:
#返回自身数据的数组的一个array
print(type(matr5),type(matr5.A))

<class 'numpy.matrix'> <class 'numpy.ndarray'>


In [39]:
matr5.A

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

### 1.3 numpy的通用函数和广播机制

**Numpy中的通用函数（ufunc）是一种针对ndarray对象执行元素集运算的函数**

In [40]:
# 求绝对值
matr6=-matr1
print(matr6,'\n\n',abs(matr6))

[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
# 开方
np.sqrt(matr1)

matrix([[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974],
        [2.64575131, 2.82842712, 3.        ]])

In [42]:
# e乘幂
np.exp(matr1)

matrix([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [46]:
# 生成布尔矩阵
matr1>3

matrix([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [50]:
mask=matr1>3

In [48]:
matr1[mask]

matrix([[4, 5, 6, 7, 8, 9]])

**广播机制**

In [52]:
smallmatr=np.matrix('1,2')
rowmatr=np.matrix('100,200,300')
colmatr=np.matrix('100;200;300')

In [53]:
print(smallmatr,'\n\n',rowmatr,'\n\n',colmatr)

[[1 2]] 

 [[100 200 300]] 

 [[100]
 [200]
 [300]]


In [54]:
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
print(matr1+rowmatr)

[[101 202 303]
 [104 205 306]
 [107 208 309]]


In [56]:
print(matr1+colmatr)

[[101 102 103]
 [204 205 206]
 [307 308 309]]


In [57]:
print(matr1+smallmatr)

ValueError: operands could not be broadcast together with shapes (3,3) (1,2) 

### 1.4 使用ndarray代替matrix

In [58]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
arr2=np.array([[1,0,1],[2,3,2],[4,6,1]])

In [60]:
arr1+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
arr1*[2]

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [65]:
# ndarray是对应相乘
arr1*arr2

array([[ 1,  0,  3],
       [ 8, 15, 12],
       [28, 48,  9]])

In [66]:
# ndarray叉乘
arr1.dot(arr2)

array([[17, 24,  8],
       [38, 51, 20],
       [59, 78, 32]])

In [67]:
np.dot(arr1,arr2)

array([[17, 24,  8],
       [38, 51, 20],
       [59, 78, 32]])

In [70]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**其他运算基本都一样**

## 2.利用 NumPy 进行统计分析

### 2.1 文件读写

numpy有个专用的二进制格式，优点是速度快

In [71]:
print(arr1,'\n\n',arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[1 0 1]
 [2 3 2]
 [4 6 1]]


In [75]:
np.save("filename",arr1)

In [76]:
np.save("abc",arr1,arr2)  #保存的是后缀名为npy的2进制文件，不能用普通的文本编辑器打开

In [77]:
arr3=np.load("abc.npy") #必须加后缀名
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


np.save只保存第一个参数；
np.savez可以保存多个参数

In [78]:
np.savez('xyz',arr1,arr2,arr1) #保存的后缀名是npz,是个压缩包格式

In [79]:
arr4=np.load("xyz.npz") #返回得到的NpzFile的一个对象，包含了指向保存的内容的路径
print(arr4)

In [80]:
x,y,z=np.load("xyz.npz") #可以返回一npzfile的对象，或者所有的目标路径（接收返回值的变量数量要和保存的数组数量完全对应，否则报错）
print(x,y,z,arr4[x])

arr_0 arr_1 arr_2 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
# 好的使用方法如下，使用npzfile的files属性获得其所有保存的数组的位置，或者说名称，然后调用
print(arr4.files,type(arr4.files))

['arr_0', 'arr_1', 'arr_2'] <class 'list'>


In [82]:
for i in arr4.files:
    print(arr4[i],'\n')
print(arr4['arr_0'])

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 0 1]
 [2 3 2]
 [4 6 1]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


保存普通的文本格式，优点是普适性强

In [86]:
np.savetxt("abc", arr1)  #需要注意，savetxt下是要自己加文件的后缀名的！！！

In [87]:
np.savetxt("abc.csv",arr2,fmt='%.2f',delimiter=",") #保存成csv时记得把分隔符设为半角逗号

In [88]:
p=np.loadtxt("abc")
q=np.loadtxt("abc.csv",delimiter=",") #读csv的时候也记得把分隔符改成半角逗号，否则报错

In [89]:
print(p,'\n\n',q)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

 [[1. 0. 1.]
 [2. 3. 2.]
 [4. 6. 1.]]


In [90]:
type(q)

numpy.ndarray

In [95]:
r=np.genfromtxt("abc.csv",delimiter = ",")
print(r)

[nan nan nan]


In [92]:
type(r)

numpy.ndarray

### 2.2 简单数据处理

#### 2.2.1 数据排序

In [96]:
q=np.loadtxt("abc.csv",delimiter=",") 
print(q)

[[1. 0. 1.]
 [2. 3. 2.]
 [4. 6. 1.]]


In [100]:
#默认是axis=1，即按横轴从小到大排序
q.sort(axis=0)

In [101]:
q

array([[1., 0., 1.],
       [2., 3., 1.],
       [4., 6., 2.]])

In [102]:
q.sort(axis=1)
q

array([[0., 1., 1.],
       [1., 2., 3.],
       [2., 4., 6.]])

In [103]:
print(arr2)

[[1 0 1]
 [2 3 2]
 [4 6 1]]


In [104]:
s=np.sort(arr2,axis=1) #不改变原数组
print(s)
print(arr2)

[[0 1 1]
 [2 2 3]
 [1 4 6]]
[[1 0 1]
 [2 3 2]
 [4 6 1]]


sort()是返回从小到大排序的数值结果；

与之对应的，argsort()返回的是排序的顺序结果

In [1]:
import numpy as np
arr5=np.random.randint(0,10.1,size=10)
print(arr5)

[0 1 0 4 7 4 1 9 0 7]


In [2]:
print(arr5.argsort())
print(np.argsort(arr5))
print(arr5)

[0 2 8 1 6 3 5 4 9 7]
[0 2 8 1 6 3 5 4 9 7]
[0 1 0 4 7 4 1 9 0 7]


想知道第五个数字的排序

In [3]:
arr5.argsort()[4]

6

常见的用途：查询排名

In [4]:
#构建成绩单，一个姓名，一个是对应的成绩
name_list=['zhao', 'qian', 'sun', 'li', 'zhou', 'wu', 'zheng', 'wang']
name=np.array(name_list)
scores=np.array([87, 67, 93, 88, 79, 90, 80, 95])

In [6]:
name_list.index('zhao')

0

In [7]:
scores.argsort()[name_list.index('zhao')]

1

即zhao的排名是倒数第2

如果想按成绩排序怎么办？

可以使用take_along_axis(待排序数组，排序的顺序，axis=排序的轴)

In [8]:
np.take_along_axis(name,scores.argsort(),axis=0) 

array(['qian', 'zhou', 'zheng', 'zhao', 'li', 'wu', 'sun', 'wang'],
      dtype='<U5')

In [9]:
scores.sort()

In [10]:
scores

array([67, 79, 80, 87, 88, 90, 93, 95])

#### 2.2.2 数据去重

In [11]:
birthday=np.array([129,213,1209,1106,917,813,917,606,129,213])

In [12]:
np.unique(birthday)

array([ 129,  213,  606,  813,  917, 1106, 1209])

In [13]:
name=np.array(['张三','李四','王五','张三'])
np.unique(name)

array(['张三', '李四', '王五'], dtype='<U2')

**小思考：怎么知道有没有重复的元素呢？**

In [14]:
birthday.size-np.unique(birthday).size

3

#### 2.2.3 数据重复

In [25]:
arr6=np.random.randint(0,10.1,size=(2,3))
print(arr6)

[[2 6 8]
 [5 8 0]]


In [31]:
np.tile(arr6,3) #整体重复

array([[2, 6, 8, 2, 6, 8, 2, 6, 8],
       [5, 8, 0, 5, 8, 0, 5, 8, 0]])

In [32]:
np.repeat(arr6, 3, axis=1) #逐行、或逐列重复

array([[2, 2, 2, 6, 6, 6, 8, 8, 8],
       [5, 5, 5, 8, 8, 8, 0, 0, 0]])

#### 2.3.4 数组运算

In [34]:
np.sum(arr6) #对数组所有元素求和

29

In [35]:
arr6/29

array([[0.06896552, 0.20689655, 0.27586207],
       [0.17241379, 0.27586207, 0.        ]])

In [37]:
np.var(arr6) #数组的方差

8.805555555555555

In [39]:
np.mean(arr6) #数组的均值

4.833333333333333